[tools]
node = "24"
"npm:@googleworkspace/cli" = "latest"
"npm:@musistudio/claude-code-router" = "latest"
"npm:@playwright/cli" = "latest"
"npm:firebase-tools" = "latest"
"npm:portless" = "latest"
pnpm = "latest"
