tap "homebrew/bundle"
tap "leoafarias/fvm"
brew "act"
brew "bat"
brew "broot"
brew "eza"
brew "fd"
brew "gh"
brew "ghq"
brew "git-delta"
brew "hey"
brew "k6"
brew "lefthook"
brew "mas"
brew "nkf"
brew "openjdk"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "starship"
brew "the_silver_searcher"
brew "volta"
brew "yq"
brew "leoafarias/fvm/fvm"
cask "alfred"
cask "appcleaner"
cask "applite"
cask "bitwarden"
cask "brave-browser"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-hack-nerd-font"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "imageoptim"
cask "ngrok"
cask "notion"
cask "slack"
cask "stoplight-studio"
cask "visual-studio-code"
cask "warp"

# AppStoreからインストール
if OS.mac?
  mas "Display Menu", id: 549083868
  mas "RunCat", id: 1429033973
  mas "Magnet", id: 441258766
end
